services:
  # The Node.js Backend 
  - type: web
    name: executex-server
    env: docker # Required so Render can use child_process docker spawning
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: MONGO_URI
        sync: false # Set this in your Render dashboard
      - key: NODE_ENV
        value: production

  # The React.js Frontend
  - type: web
    name: executex-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://executex-server.onrender.com
